# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 08:24
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('grammy', '0006_auto_20180305_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=tinymce.models.HTMLField(),
        ),
    ]
