# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammy', '0009_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='image_profile',
        ),
    ]
