# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammy', '0012_auto_20180306_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
