# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammy', '0014_remove_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=0, upload_to='user/'),
        ),
    ]
