# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammy', '0016_auto_20180307_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='user/'),
        ),
    ]
