# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grammy', '0018_auto_20180307_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(db_column='image_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='grammy.User'),
        ),
    ]
