# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grammy', '0021_auto_20180308_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grammy.User'),
        ),
    ]
